"""Deterministic flow -> Python codegen (#146, dev item 6).

A developer presses Copy and leaves with a runnable scaffold of THEIR flow:
one function per block, wired in graph order, grounded in the catalog's
cheat-sheet notes and doc links. No LLM writes this file (D3): the generator
is a pure function of the workflow + catalog, so the same flow always yields
the same code.

Safety blocks become guard functions that raise instead of letting money move;
event blocks become webhook handler stubs; custom code blocks (#147) land
verbatim where the dev placed them.
"""

from __future__ import annotations

import re
from collections import deque

from ..ir.models import Node, Workflow
from ..providers import default_catalog
from ..providers.base import Catalog

# Documented endpoint per node type (Monnify API cheat sheet / developers
# .monnify.com). Codegen-local on purpose: the catalog stays transport-neutral.
_ENDPOINTS: dict[str, tuple[str, str]] = {
    "monnify.initialize_transaction": ("POST", "/api/v1/merchant/transactions/init-transaction"),
    "monnify.verify_transaction": ("GET", "/api/v2/merchant/transactions/query"),
    "monnify.create_reserved_account": ("POST", "/api/v2/bank-transfer/reserved-accounts"),
    "monnify.create_invoice": ("POST", "/api/v1/invoice/create"),
    "monnify.initiate_transfer": ("POST", "/api/v2/disbursements/single"),
    "monnify.bulk_transfer": ("POST", "/api/v2/disbursements/batch"),
    "monnify.query_transfer_status": ("GET", "/api/v2/disbursements/single/summary"),
    "monnify.validate_bank_account": ("GET", "/api/v1/disbursements/account/validate"),
    "monnify.transaction_split": ("POST", "/api/v1/split-transactions/split"),
    "monnify.initiate_refund": ("POST", "/api/v1/refunds/initiate-refund"),
}

_HEADER = '''"""{name} - generated by Monnify Studio.

Deterministic codegen from your flow graph (#146): no LLM wrote this file,
the same flow always generates the same code. Each function below is one
block on your whiteboard, wired in flow order by run().

Sandbox first: set MONNIFY_API_KEY / MONNIFY_SECRET_KEY / MONNIFY_CONTRACT_CODE
in your environment. Base URL defaults to the sandbox; change it only when you
have tested end to end.
"""

from __future__ import annotations

import base64
import os
from decimal import Decimal

import httpx

BASE_URL = os.getenv("MONNIFY_BASE_URL", "https://sandbox.monnify.com")
CONTRACT_CODE = os.getenv("MONNIFY_CONTRACT_CODE", "")


class GuardFailed(Exception):
    """A safety block said no. Money must NOT move past this point."""


def _token(client: httpx.Client) -> str:
    """Authenticate (docs: https://developers.monnify.com/api/#authentication)."""
    basic = base64.b64encode(
        f"{{os.getenv('MONNIFY_API_KEY', '')}}:{{os.getenv('MONNIFY_SECRET_KEY', '')}}".encode()
    ).decode()
    resp = client.post(
        f"{{BASE_URL}}/api/v1/auth/login",
        headers={{"Authorization": f"Basic {{basic}}"}},
    )
    resp.raise_for_status()
    return resp.json()["responseBody"]["accessToken"]
'''


def _identifier(node: Node) -> str:
    """A stable python function name for a node."""
    raw = re.sub(r"[^a-z0-9_]+", "_", node.id.lower()).strip("_") or "block"
    if raw[0].isdigit():
        raw = f"n_{raw}"
    return raw


def _flow_order(workflow: Workflow) -> list[Node]:
    """Entrypoint spine first, then remaining islands - the engine's walk (#8)."""
    order: list[Node] = []
    seen: set[str] = set()
    roots = [workflow.entrypoint] if workflow.entrypoint else []
    roots += [r for r in workflow.roots() if r not in roots]
    queue: deque[str] = deque(roots)
    adjacency: dict[str, list[str]] = {}
    for edge in workflow.edges:
        adjacency.setdefault(edge.source, []).append(edge.target)
    while queue:
        node_id = queue.popleft()
        if node_id in seen:
            continue
        seen.add(node_id)
        order.append(workflow.node(node_id))
        queue.extend(adjacency.get(node_id, []))
    return order


def _docstring(node: Node, catalog: Catalog) -> str:
    try:
        d = catalog.resolve(node.type)
    except KeyError:
        return f'    """{node.label or node.type}."""'
    lines = [f'    """{node.label or d.title} ({node.type}).']
    if d.when_to_use:
        lines += ["", f"    When to use: {d.when_to_use}"]
    if d.doc_url:
        lines += ["", f"    Docs: {d.doc_url}"]
    lines.append('    """')
    return "\n".join(lines)


def _config_literal(node: Node) -> str:
    if not node.config:
        return "{}"
    inner = ", ".join(f'"{k}": {v!r}' for k, v in node.config.items())
    return "{" + inner + "}"


def _body(node: Node) -> list[str]:
    """The function body for one block. Config the dev typed rides along."""
    t = node.type
    if t in _ENDPOINTS:
        method, path = _ENDPOINTS[t]
        call = "client.get" if method == "GET" else "client.post"
        payload = "params" if method == "GET" else "json"
        return [
            f"    body = {{**{_config_literal(node)}, **ctx}}",
            '    body.setdefault("contractCode", CONTRACT_CODE)',
            f'    resp = {call}(',
            f'        f"{{BASE_URL}}{path}",',
            '        headers={"Authorization": f"Bearer {token}"},',
            f"        {payload}=body,",
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t == "safety.verify_signature":
        return [
            "    # Verify the webhook came from Monnify before trusting a kobo of it.",
            "    import hashlib, hmac",
            '    secret = os.getenv("MONNIFY_SECRET_KEY", "").encode()',
            '    expected = hmac.new(secret, raw_payload, hashlib.sha512).hexdigest()',
            '    if not hmac.compare_digest(expected, signature_header):',
            '        raise GuardFailed("webhook signature mismatch: not Monnify")',
            "    return ctx",
        ]
    if t == "safety.validate_amount":
        return [
            "    # Paid must cover expected, compared exactly - never with floats.",
            f'    expected = Decimal(str(ctx.get("expected_amount", {node.config.get("expected_amount", 0)!r})))',
            '    paid = Decimal(str(ctx.get("amountPaid", ctx.get("paid_amount", "0"))))',
            "    if paid < expected:",
            '        raise GuardFailed(f"underpaid: {paid} of {expected}")',
            "    return ctx",
        ]
    if t == "safety.idempotency_guard":
        return [
            "    # Process each payment reference exactly once.",
            '    ref = ctx.get("paymentReference") or ctx.get("payment_reference")',
            "    if ref in _SEEN_REFERENCES:",
            '        raise GuardFailed(f"duplicate delivery: {ref} already handled")',
            "    _SEEN_REFERENCES.add(ref)",
            "    return ctx",
        ]
    if t == "safety.balance_guard":
        return [
            "    # Check the wallet covers the payout BEFORE moving money (MON012).",
            '    resp = client.get(f"{BASE_URL}/api/v2/disbursements/wallet-balance",',
            '                      headers={"Authorization": f"Bearer {token}"},',
            '                      params={"accountNumber": os.getenv("MONNIFY_WALLET", "")})',
            "    resp.raise_for_status()",
            '    balance = Decimal(str(resp.json().get("responseBody", {}).get("availableBalance", "0")))',
            '    amount = Decimal(str(ctx.get("amount", "0")))',
            "    if balance < amount:",
            '        raise GuardFailed(f"insufficient balance: {balance} < {amount}")',
            "    return ctx",
        ]
    if t.startswith("safety."):
        return [
            "    # Guard checkpoint: keep this before any money-moving call.",
            "    return ctx",
        ]
    if t.startswith("event."):
        return [
            "    # Webhook/event handler stub: mount this on your framework's route",
            "    # (e.g. POST /monnify/webhook) and pass the parsed payload in.",
            "    ctx.update(payload or {})",
            "    return ctx",
        ]
    if t == "custom.code":
        code = str(node.config.get("code", "")).rstrip()
        if code:
            snippet = ["    # --- your code block (verbatim from the whiteboard, #147) ---"]
            snippet += [f"    {line}" if line.strip() else "" for line in code.splitlines()]
            snippet += ["    # --- end code block ---", "    return ctx"]
            return snippet
        return ["    # Empty code block.", "    return ctx"]
    # app.* and anything else: a plain step that records what it did.
    return [
        f'    ctx.setdefault("log", []).append("{node.label or t}")',
        "    return ctx",
    ]


def generate_python(workflow: Workflow, catalog: Catalog | None = None) -> str:
    """The whole module: header, one function per block, run() wiring."""
    catalog = catalog or default_catalog()
    nodes = _flow_order(workflow)
    parts: list[str] = [_HEADER.format(name=workflow.name)]
    parts.append("_SEEN_REFERENCES: set[str] = set()\n")

    calls: list[str] = []
    for node in nodes:
        fn = _identifier(node)
        signature = f"def {fn}(ctx: dict, *, client: httpx.Client, token: str, "
        if node.type == "safety.verify_signature":
            signature += "raw_payload: bytes = b'', signature_header: str = '', "
        if node.type.startswith("event."):
            signature += "payload: dict | None = None, "
        signature = signature.rstrip(", ") + ") -> dict:"
        parts.append("\n".join(["", signature, _docstring(node, catalog), *(_body(node))]))
        calls.append(f"        ctx = {fn}(ctx, client=client, token=token)")

    runner = "\n".join(
        [
            "",
            "",
            "def run() -> dict:",
            f'    """Run the whole flow in order, exactly as drawn: {workflow.name}."""',
            "    ctx: dict = {}",
            "    with httpx.Client(timeout=30.0) as client:",
            "        token = _token(client)",
            *calls,
            "    return ctx",
            "",
            "",
            'if __name__ == "__main__":',
            "    print(run())",
            "",
        ]
    )
    parts.append(runner)
    return "\n".join(parts)
